#!/usr/bin/env python
# -*- coding: utf-8 -*-
import shutil

import typer

from fastgrpc.helpers.misc import get_python_lib
from fastgrpc.helpers.vcs import clone, commit, push
from pydantic_settings import BaseSettings

ASSETS_PATH = "/tmp/grpc_assets"


class PublisherSettings(BaseSettings):
    assets_repo_url: str


settings = PublisherSettings()


def publish_grpc_service(repo: str, name: str, message: str):

    clone(settings.assets_repo_url, ASSETS_PATH)
    pb_path = f"{get_python_lib()}/grpc_assets/{name}"
    shutil.copytree(pb_path, f"{ASSETS_PATH}/{name}")
    commit(ASSETS_PATH, message)
    push(ASSETS_PATH)


if __name__ == "__main__":
    typer.run(publish_grpc_service)
