#!/usr/bin/env python
# -*- coding: utf-8 -*-
import shutil

import typer
import vcs

from fastgrpc.helpers.misc import get_python_lib


def publish_grpc_service(repo: str, name: str, message: str):
    repo = vcs.clone_or_fetch(GRPC_ASSETS_REPO)
    pb_path = f"{get_python_lib()}/grpc_assets/{name}"
    shutil.rmtree(f"{repo.repo_path}/grpc_assets", ignore_errors=True)
    shutil.copytree(pb_path, f"{repo.repo_path}/grpc_assets/{name}")
    vcs.commit_files(repo.repo_path, message, f"grpc_assets/{name}")
    vcs.push_to_origin(repo.repo_path)


if __name__ == "__main__":
    publish_grpc_service()
